### ISSUE TITLE
Input File Missing

### ISSUE THREAD

**Issue by hrace009** [ixartz/Astro-boilerplate#5] opened 2022-07-19 13:37 UTC
Helo,

When i run `npm run build`, i got this error
```
D:\Landing\Astro-boilerplate>npm run build

> astro-boilerplate@1.0.0 build
> astro build

08:35:27 PM [build] Collecting build information...
08:35:37 PM [build] src/pages/index.astro is taking a bit longer to import. This is common for larger "Astro.glob(...)" or "import.meta.globEager(...)" calls, for instance. Hang tight!
08:35:41 PM [build] Completed in 14.50s.

 building client
vite v2.9.12 building for production...
✓ 23 modules transformed.
dist/entry.663e93a5.js   138.21 KiB / gzip: 44.18 KiB
Completed in 2.31s.

08:35:43 PM [build] Building entrypoints for prerendering...
08:35:47 PM [build] Completed in 3.81s.

 generating static routes
▶ src/pages/index.astro
  └─ /index.html (+92ms)
λ src/pages/rss.xml.ts
  └─ /rss.xml/index.html (+18ms)
▶ src/pages/posts/hello-world.md
  └─ /posts/hello-world/index.html (+19ms)
▶ src/pages/posts/second-post.md
  └─ /posts/second-post/index.html (+14ms)
▶ src/pages/posts/fifth-post.md
  └─ /posts/fifth-post/index.html (+16ms)
▶ src/pages/posts/first-post.md
  └─ /posts/first-post/index.html (+11ms)
▶ src/pages/posts/forth-post.md
  └─ /posts/forth-post/index.html (+11ms)
▶ src/pages/posts/sixth-post.md
 error   Input file is missing
```

please help.

Thanks

**Comment by ixartz** [comment] 2022-07-19 16:13
@hrace009, I just made a clean and fresh install, it works perfectly and I'm not able to reproduce your error:

```sh
npm run build

> astro-boilerplate@1.0.0 build
> astro build

06:12:06 PM [build] Collecting build information...
06:12:07 PM [build] Completed in 1.34s.

 building client
vite v2.9.12 building for production...
✓ 23 modules transformed.
dist/entry.663e93a5.js   138.21 KiB / gzip: 44.18 KiB
Completed in 421ms.

06:12:07 PM [build] Building entrypoints for prerendering...
06:12:08 PM [build] Completed in 491ms.

 generating static routes
▶ src/pages/index.astro
  └─ /index.html (+11ms)
λ src/pages/rss.xml.ts
  └─ /rss.xml/index.html (+2ms)
▶ src/pages/posts/hello-world.md
  └─ /posts/hello-world/index.html (+3ms)
▶ src/pages/posts/second-post.md
  └─ /posts/second-post/index.html (+2ms)
▶ src/pages/posts/fifth-post.md
  └─ /posts/fifth-post/index.html (+3ms)
▶ src/pages/posts/first-post.md
  └─ /posts/first-post/index.html (+2ms)
▶ src/pages/posts/forth-post.md
  └─ /posts/forth-post/index.html (+2ms)
▶ src/pages/posts/sixth-post.md
Responsive Image sets generated for Picture at /src/images/random.jpeg in 26.15141600370407ms
  └─ /posts/sixth-post/index.html (+29ms)
▶ src/pages/posts/third-post.md
  └─ /posts/third-post/index.html (+2ms)
▶ src/pages/posts/[...page].astro
  ├─ /posts/index.html (+5ms)
  └─ /posts/2/index.html (+8ms)
Completed in 71ms.

astro-robots-txt: `robots.txt` is created.

06:12:11 PM [build] 10 page(s) built in 5.49s
06:12:11 PM [build] Complete!
```

Could you retry with a fresh install? Did you made some change in the project?

**Comment by hrace009** [comment] 2022-07-20 10:10
> Could you retry with a fresh install? Did you made some change in the project?
@ixartz I have try with fresh install,
What i do is:
```
git clone --depth=1 https://github.com/ixartz/Astro-boilerplate
cd Astro-boilerplate
npm install
```
when running `npm run dev`, i can run test server http://localhost:3000/
but when running `npm run build` i got error `error   Input file is missing`

**Comment by ixartz** [comment] 2022-07-20 15:13
@hrace009, This still working on my local machine whether using `npm run dev` or `npm run build`

It's the first time I see this error. This error output doesn't give me any hint, it's hard for me to find the root cause. I have no clue where I can search.

Could you try on another computer? Totally different system Linux? Mac?

**Comment by ixartz** [comment] 2022-07-29 03:37
I'm closing the issue: I'm not able to reproduce the issue and without any response.

Please open a new issue if you the problem occurs again.

**Closed as completed** 2022-07-29 03:36 UTC
Labels: question

**Comment by artidataio** [comment] 2022-10-30 18:29
I can reproduce the same issue where  input file is missing at the sixth-post.md. I'm able to isolate the bug, if the line 121 (image reference code) is deleted, it can build perfectly. However, I find that I can't use inline-style images in any markdown file.

**Comment by ixartz** [comment] 2022-10-31 00:03
@artidataio Could you update https://github.com/ixartz/Astro-boilerplate/blob/main/package.json#L29 to the latest dependency? Does it solve the issue?

**Comment by artidataio** [comment] 2022-10-31 03:43
I have upgraded to `"astro-imagetools": "^0.6.11"` it still has the same errors. 

I'm working on a windows PC. If I try to follow the guide on inserting images in a markdown file as per [docs](https://docs.astro.build/en/guides/images/#in-markdown-files): 
```markdown
![Astro](https://astro.build/assets/logo.png)
```
I still have the following error: 

```
Failed to load https://astro.build/assets/logo.png; Invalid image format
Error: Failed to load https://astro.build/assets/logo.png; Invalid image format
    at throwErrorIfUnsupported (/node_modules/astro-imagetools/api/utils/getProcessedImage.js:23:11)
    at Module.__vite_ssr_exports__.default (/node_modules/astro-imagetools/api/utils/getProcessedImage.js:60:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.__vite_ssr_exports__.default (/node_modules/astro-imagetools/api/utils/getImage.js:34:5)
    at async Module.rend&#8230;
```

**Comment by ixartz** [comment] 2022-10-31 16:50
@artidataio Your image isn't stored locally, does the plugin support the remote image?

Could you download the image and use it?

**Comment by artidataio** [comment] 2022-10-31 17:32
I tried both local and remote, local file has the input file missing error, remote file has the above error.

**Comment by ixartz** [comment] 2022-10-31 23:33
The problem, I don't have a window, I'm on Mac. It'll hard for me to test on my local environment.
